"""Token-efficient league-level dynasty analysis.

Python owns facts and persistence. The model receives one compact roster
snapshot per changed league and returns only an overview and actionable players.
"""
import json
import logging
from collections.abc import Mapping
from datetime import datetime, timezone
from typing import Any

from .common import write_json_atomic
from .league_reasoning_model import (
    ANALYSIS_CACHE_PATH,
    PLAYER_STORE_PATH,
    SNAPSHOT_DIR,
    _contract_note,
    _fingerprint,
    _load,
    _material,
    _news,
    analyse_league,
    build_client,
    build_league_snapshot,
    build_model_payload,
    canonical_player,
    provider_model,
    provider_name,
)
from .news_agent import match_to_roster
from .schemas import (
    AnalysedPlayer,
    LeagueResult,
    NewsOutput,
    ReasoningOutput,
    ReasoningResult,
    SleeperOutput,
)
from .signal_evidence import classify_change_status

log = logging.getLogger(__name__)
def _default(player: Mapping[str, Any]) -> ReasoningResult:
    return {
        "trend": "NO_ACTION",
        "confidence": "LOW",
        "summary": "No material change requiring action.",
        "fantasy_impact": "NONE",
        "recommendation": "Hold.",
        "dynasty_note": None,
        "contract_note": _contract_note(player),
        "roster_status_note": player.get("roster_designation"),
        "flags": [],
    }


def _with_action(player: Mapping[str, Any], action: Mapping[str, Any]) -> ReasoningResult:
    result = _default(player)
    result.update(
        {
            "trend": action["trend"],
            "confidence": action["confidence"],
            "summary": action["reason"],
            "recommendation": action["action"],
            "fantasy_impact": "LONG" if "bust_risk" in action["flags"] else "SHORT",
            "flags": action["flags"],
        }
    )
    return result


def run(sleeper_data: SleeperOutput, news_data: NewsOutput) -> ReasoningOutput:
    player_store: dict[str, Any] = _load(PLAYER_STORE_PATH, {})
    cache: dict[str, Any] = _load(ANALYSIS_CACHE_PATH, {})
    client = None
    provider = provider_name()
    model = provider_model(provider)
    now = datetime.now(timezone.utc).isoformat()
    result: ReasoningOutput = {
        "username": sleeper_data.get("username"),
        "season": sleeper_data.get("season"),
        "leagues": [],
        "global_trends": {
            "trending_up": [],
            "trending_down": [],
            "watch_list": [],
        },
        "change_summary": {
            "material_change": 0,
            "noteworthy_unchanged": 0,
            "stable": 0,
            "no_signal": 0,
        },
    }
    seen: dict[str, set[str]] = {"UP": set(), "DOWN": set(), "WATCH": set()}
    SNAPSHOT_DIR.mkdir(exist_ok=True)
    for league in sleeper_data.get("leagues", []):
        players = match_to_roster(news_data.get("news_by_player", {}), league.get("players", []))
        for player in players:
            player_store[str(player.get("player_id"))] = canonical_player(player)
        snapshot = build_league_snapshot(league, players)
        write_json_atomic(SNAPSHOT_DIR / f"{league['league_id']}.json", snapshot, sort_keys=True)
        payload = build_model_payload(league, players)
        league_id = str(league["league_id"])
        # Provider/model are part of the cache identity, so switching either
        # intentionally produces a fresh analysis instead of serving prose
        # generated by the previously selected backend.
        fingerprint = _fingerprint({"provider": provider, "model": model, "payload": payload})
        cached: Any = cache.get(league_id)
        analysis: dict[str, Any]
        persist_analysis = False
        if not players:
            analysis = {"overview": "No roster data available for this league.", "actions": []}
            analysis_source = "empty_roster"
            log.info("Skipping AI call for league=%s: roster is empty", league.get("league_name"))
        elif cached and cached.get("fingerprint") == fingerprint:
            analysis = cached["analysis"]
            analysis_source = "cache"
            log.info("Skipping AI call for league=%s: unchanged payload; using cached analysis", league.get("league_name"))
        elif not any(_material(p) for p in players):
            analysis = {"overview": "No material roster news or injury changes this cycle.", "actions": []}
            analysis_source = "quiet"
            log.info("Skipping AI call for league=%s: quiet league with no material signals", league.get("league_name"))
        else:
            try:
                client = client or build_client(provider)
                log.info(
                    "Calling AI provider=%s model=%s for league=%s",
                    provider,
                    model,
                    league.get("league_name"),
                )
                log.info(
                    "AI request JSON for league=%s:\n%s",
                    league.get("league_name"),
                    json.dumps(payload, indent=2, ensure_ascii=False),
                )
                analysis = analyse_league(client, provider, model, payload)
                analysis_source = "model"
                persist_analysis = True
            except Exception as exc:
                log.error("League analysis failed for %s: %s", league.get("league_name"), exc)
                analysis = (
                    cached.get("analysis")
                    if cached
                    else {
                        "overview": "Analysis unavailable; showing current roster facts.",
                        "actions": [],
                    }
                )
                analysis_source = "stale_cache_after_error" if cached else "error_fallback"
                log.info("Not caching failed AI analysis for league=%s; the next run will retry", league.get("league_name"))
        log.info(
            "Overall league analysis for league=%s source=%s: %s",
            league.get("league_name"),
            analysis_source,
            analysis["overview"],
        )
        if persist_analysis:
            cache[league_id] = {"fingerprint": fingerprint, "generated_at": now, "analysis": analysis}
        actions = {action["player_id"]: action for action in analysis["actions"]}
        analysed: list[AnalysedPlayer] = []
        for player in players:
            pid = str(player.get("player_id"))
            item: AnalysedPlayer = {**player}
            item["reasoning"] = _with_action(player, actions[pid]) if pid in actions else _default(player)
            item["generated_at"] = now if pid in actions else None
            item["change_status"] = classify_change_status(
                None,
                {"news": _news(player), "inj": canonical_player(player)["inj"]},
                is_zero_signal=not _material(player),
                has_injury_flag=bool(player.get("has_injury_flag")),
                trend=item["reasoning"]["trend"],
            )
            result["change_summary"][item["change_status"]] += 1
            analysed.append(item)
        buckets = {
            trend: [player for player in analysed if player["reasoning"]["trend"] == trend]
            for trend in ("UP", "DOWN", "WATCH", "NO_ACTION")
        }
        league_result: LeagueResult = {
            "league_id": league["league_id"],
            "league_name": league["league_name"],
            "season": league["season"],
            "summary": analysis["overview"],
            "players": analysed,
            "trending_up": buckets["UP"],
            "trending_down": buckets["DOWN"],
            "watch_list": buckets["WATCH"],
            "no_action": buckets["NO_ACTION"],
            "stats": {
                "total": len(analysed),
                "trending_up": len(buckets["UP"]),
                "trending_down": len(buckets["DOWN"]),
                "watch": len(buckets["WATCH"]),
                "no_action": len(buckets["NO_ACTION"]),
                "injured": sum(bool(player.get("has_injury_flag")) for player in analysed),
            },
        }
        result["leagues"].append(league_result)
        for player in buckets["UP"]:
            pid = str(player.get("player_id"))
            if pid not in seen["UP"]:
                result["global_trends"]["trending_up"].append(player)
                seen["UP"].add(pid)
        for player in buckets["DOWN"]:
            pid = str(player.get("player_id"))
            if pid not in seen["DOWN"]:
                result["global_trends"]["trending_down"].append(player)
                seen["DOWN"].add(pid)
        for player in buckets["WATCH"]:
            pid = str(player.get("player_id"))
            if pid not in seen["WATCH"]:
                result["global_trends"]["watch_list"].append(player)
                seen["WATCH"].add(pid)
    write_json_atomic(PLAYER_STORE_PATH, player_store, sort_keys=True)
    write_json_atomic(ANALYSIS_CACHE_PATH, cache, sort_keys=True)
    return result
